language: python

addons:
  apt:
    packages: valgrind

python:
  - "2.7"
  - "3.8"

env:
  - BACKEND=tpy ARGS=--memcheck
  - BACKEND=tpy-shared
  - BACKEND=tpvm
  - BACKEND=tpvm-dbg ARGS=--memcheck

os:
  - linux


install:
    - python --version
    - make

script:
    - make all
    - make shared
    - make debug
    - bash run-tests.sh --backend=${BACKEND} ${ARGS} tests/*.py
