language: python

python:
  - "2.7"
  - "3.8"

env:
  - TEST_TARGET=test
  - TEST_TARGET=test-dbg
  - TEST_TARGET=test-shared
  - TEST_TARGET=test-tpy

os:
  - linux


install:
    - python --version
    - make

script:
    - make $TEST_TARGET
